version: '3.7'
services: 
  golang:
    container_name: golang
    image: golang:1.14-rc-stretch
    volumes:
      - .:/go/src/app
    command: sleep infinity
    networks: 
      - dev
    ports: 
      - "8080:8080"
  postgres:
    container_name: postgres
    image: postgres:latest
    environment: 
      - POSTGRES_PASSWORD=zues 
      - POSTGRES_DB=testdb
      - POSTGRES_USER=root
    networks: 
      - dev
    ports: 
      - "5432:5432"
    
    
networks: 
  dev: